# This file was generated by GoReleaser. DO NOT EDIT.
cask "factuarea" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "ab4d52e276efbac4ccc15cfac6c32202dfb338f85928339e9c61a2fc85fd35a4"
      url "https://github.com/factuarea/factuarea-cli/releases/download/v#{version}/factuarea_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a4d857a9646fefa3fa5d1bd180c87dc4e06b0375e624e76e0570f7b0186fb62c"
      url "https://github.com/factuarea/factuarea-cli/releases/download/v#{version}/factuarea_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b4df74e1a35c5ed24f47427d7f7cbfbd327ce82a2d5181df8a2154b770c0ac56"
      url "https://github.com/factuarea/factuarea-cli/releases/download/v#{version}/factuarea_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a0131e9dd7cb4706f59e98e830e7092beedcb298888cecc7a6563cde3a15740d"
      url "https://github.com/factuarea/factuarea-cli/releases/download/v#{version}/factuarea_#{version}_linux_arm64.tar.gz"
    end
  end

  name "factuarea"
  desc "CLI oficial de Factuarea para la API pública v1"
  homepage "https://factuarea.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "factuarea"
  manpage "manpages/factuarea.1"
  bash_completion "completions/factuarea.bash"
  fish_completion "completions/factuarea.fish"
  zsh_completion "completions/factuarea.zsh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/factuarea"], must_succeed: false
  end

  # No zap stanza required

end
