# This file was generated by GoReleaser. DO NOT EDIT.
cask "factuarea" do
  version "0.5.1"

  on_macos do
    on_arm do
      sha256 "c6c15bb188b53b7d22606158f3dba6651e6257583360dcb5fa052e175cc5489e"
      url "https://github.com/factuarea/factuarea-cli/releases/download/v#{version}/factuarea_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "69fe205976b44e30661fb634592610ce434ccaa2ae0b165881b032dc47de4afd"
      url "https://github.com/factuarea/factuarea-cli/releases/download/v#{version}/factuarea_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b694f6bf752fc86b9df97051bbfa5a7b1b06a710dd417eae146f76cdd00d88a8"
      url "https://github.com/factuarea/factuarea-cli/releases/download/v#{version}/factuarea_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2c2887ade4eb4572f8aa4aada2284c669e9db795c77328e5b351c1472b037531"
      url "https://github.com/factuarea/factuarea-cli/releases/download/v#{version}/factuarea_#{version}_linux_amd64.tar.gz"
    end
  end

  name "factuarea"
  desc "CLI oficial de Factuarea para la API pública v1"
  homepage "https://factuarea.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "factuarea"
  manpage "manpages/factuarea.1"
  bash_completion "completions/factuarea.bash"
  fish_completion "completions/factuarea.fish"
  zsh_completion "completions/factuarea.zsh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/factuarea"], must_succeed: false
  end

  # No zap stanza required
end
