# This file was generated by GoReleaser. DO NOT EDIT.
cask "factuarea" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "f8b84fb558585d20200d3f88d8f75122edcb17c3c33765636b6d96a676dad156"
      url "https://github.com/factuarea/factuarea-cli/releases/download/v#{version}/factuarea_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "029c594508be9d434f1e07f1c5a27d47bf393c10c434d156a768b5bdd0534dd5"
      url "https://github.com/factuarea/factuarea-cli/releases/download/v#{version}/factuarea_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5fc51d609ff629f4a7afb432092bba0764468c9d3603c09681f78eb2e6706156"
      url "https://github.com/factuarea/factuarea-cli/releases/download/v#{version}/factuarea_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1904be98a2abc202cc15df537010bba45c6c2e8802269bb155f65b2be74897ff"
      url "https://github.com/factuarea/factuarea-cli/releases/download/v#{version}/factuarea_#{version}_linux_amd64.tar.gz"
    end
  end

  name "factuarea"
  desc "CLI oficial de Factuarea para la API pública v1"
  homepage "https://factuarea.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "factuarea"
  manpage "manpages/factuarea.1"
  bash_completion "completions/factuarea.bash"
  fish_completion "completions/factuarea.fish"
  zsh_completion "completions/factuarea.zsh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/factuarea"], must_succeed: false
  end

  # No zap stanza required
end
